Numpy Basics

In [3]:
import numpy as np #np is an alias pointing to numpy = standard library for scientific computing

1. Arrays

In [ ]:
[[1,2,3],[1,2,3,[3,3,2]]] #a list can contain a list
                            # flexible: can be a vector, a matrix

In [10]:
a = np.array([1,2,3]) #create a 1D array
print(a)
type(a)
a.shape

A=np.array([[1,2,3],[1,2,3]])
A.shape

print("a = ", a, "A = ", A, sep="\n")

[1 2 3]
a = 
[1 2 3]
A = 
[[1 2 3]
 [1 2 3]]


In [15]:
np.array(["a", "4", "boat"])
np.array([3, 2, 1])
np.array([3.0, 2.0, 1.0]) == np.array([3, 2, 1], dtype = np.int64) #python converges from integer to float
np.array([3.98, 2, 1], dtype = np.int64) #careful with converting float into integer

array([3, 2, 1])

In [24]:
bool = np.array([3.0, 2.0, 1.0]) == np.array([3, 2, 2], dtype = np.int64)
bool
print(bool, bool.dtype)

np.array([0,1,1.2,-3,0.001], dtype =np.bool) #everything except 0 is true
np.array([1E-15,1,1.2,-3,0.001], dtype =np.bool) #integer exists to save capacity because float requires to save all decimals

[ True  True False] bool


array([False,  True,  True,  True,  True])

In [33]:
#exercise

F = np.full((2,3,4), 0.9) #need to specify dimensions. here 2x3x4
F[0,0,2] = 100
F


array([[[  0.9,   0.9, 100. ,   0.9],
        [  0.9,   0.9,   0.9,   0.9],
        [  0.9,   0.9,   0.9,   0.9]],

       [[  0.9,   0.9,   0.9,   0.9],
        [  0.9,   0.9,   0.9,   0.9],
        [  0.9,   0.9,   0.9,   0.9]]])

`np.empty_like` to create empty array like another array

In [37]:
Z = np.empty_like(F)
Z

N = np.empty((2,3,4))

                        # careful with those empty matrices because they display "random" numbers

for i in range(2):
    for j in range(3):
        for k in range(4):            
            N[i,j,k]= i *12 + j * 4 + k

print(N)

[[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]]

 [[12. 13. 14. 15.]
  [16. 17. 18. 19.]
  [20. 21. 22. 23.]]]


### Array indexing

In [51]:
A = np.matrix([[1,2,3],[4,5,6]])
print(A)

A[0,0] = 100 * A[0,0]
print(A)

A = A + 1
print(A)

A = A*12
print(A)

#A**2 # does not work because this multiplies the matrix by itself but a square matrix is required for this operation
 
B = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
B=B**2 # if B was built with a np.array then the square would be elementwise 

print(B)

[[1 2 3]
 [4 5 6]]
[[100   2   3]
 [  4   5   6]]
[[101   3   4]
 [  5   6   7]]
[[1212   36   48]
 [  60   72   84]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [81]:
B = np.matrix([[1,2,3],[4,5,6],[7,8,9]])

B >=3
B <= 6

B[(B >=3) & (B <= 6)]

B, B[:,2], B[:-2,2]

C = np.matrix([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
C, C[3,3], C[:,1:4], C[-1:,-1:]

(matrix([[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12],
         [13, 14, 15, 16]]),
 np.int64(16),
 matrix([[ 2,  3,  4],
         [ 6,  7,  8],
         [10, 11, 12],
         [14, 15, 16]]),
 matrix([[16]]))

In [88]:
Z = np.zeros((4,4))
for i in range(3):
    Z[i,i+1]=1 

Z



array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [93]:
# a solution with a loop
def make_shift_mat(n):
    Z=np.zeros((n,n))
    for i in range(n-1):
        Z[i,i+1]=1

    return Z

make_shift_mat(2)

array([[0., 1.],
       [0., 0.]])

In [95]:
#an alternative way with slicing
def make_shift_mat(n):
    Z = np.zeros((n,n))
    Z[np.arange(n-1), np.arange(1,n)] = 1
    return Z

make_shift_mat(3)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [104]:
S_1 = make_shift_mat(1)
S_1

S_2 = make_shift_mat(2)
S_2

S_potent = np.zeros((1+2,1+2))
S_potent
S_potent[0,0] = S_1
S_potent[1:3,1:3] = S_2
S_potent

C:\Users\Maude\AppData\Local\Temp\ipykernel_17124\2327979230.py:9: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  S_potent[0,0] = S_1


array([[0., 0., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [118]:
def make_nilpotent_mat(list_of_int):
    dim = sum(list_of_int)
    counter = 0 

    S = np.zeros((dim, dim))
    for i in list_of_int:
       S[counter:counter+i, counter:counter+i] = make_shift_mat(i)
       counter += i
    return S
    

In [120]:
make_nilpotent_mat([2,3,7])

array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [117]:
list_of_int = [2,3,5]
counter_list = [0, 2, 5]
dim = sum(list_of_int)
counter = 0

S = np.zeros((dim, dim))
for n, i in enumerate(list_of_int):
    S[counter:counter+i, counter:counter+i] = make_shift_mat(i)
    counter += list_of_int[n]

S


array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [121]:
list_of_int = [10, 5, 20]

for n, val in enumerate(list_of_int):
    print(n)
    print(val)

0
10
1
5
2
20


In [111]:
print(range(3))

range(0, 3)


In [143]:
S = make_nilpotent_mat([4,2,3])
T=S
counter = 1
print(np.zeros(S.shape))
print(np.all(T==np.zeros(S.shape)))

for i in range(1000):
    T=T@S
    counter = counter+1
    if np.all(T==np.zeros(S.shape)):
        print(counter)
        break

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]
False
4


In [153]:
def get_np_index(list_of_int):
    S = make_nilpotent_mat(list_of_int)
    T=S
    counter = 1
    #print(np.zeros(S.shape))
    #print(np.all(T==np.zeros(S.shape)))

    for i in range(1000):
        T=T@S
        counter = counter+1
        if np.all(T==np.zeros(S.shape)):
            return counter, T

In [163]:
k=get_np_index([4,2,4])
print(k)
M=make_nilpotent_mat([4,2,4])
M@M@M@M

(4, array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]))


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [152]:
print(k)

6
